version: '3'
services:
  # nginx
  web:
      container_name: nginx_web
      platform: 'linux/amd64'
      build:
        context: .
        dockerfile: ./containers/nginx.dockerfile
      ports:
          - "8080:80"
      depends_on:
          - php
  # PHP
  php:
      container_name: php-fpm
      platform: 'linux/amd64'
      build:
        context: .
        dockerfile: ./containers/php.dockerfile
      environment:
          # 環境変数でNew Relicのライセンスキーを設定
          - NEW_RELIC_LICENSE_KEY
  # OpenTelemetry Collector
  otel-collector:
    container_name: otel-collector
    platform: 'linux/amd64'
    image: otel/opentelemetry-collector:0.83.0
    restart: always
    command: ["--config=/etc/otel-config.yml", ""]
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    environment:
        # 環境変数でNew Relicのライセンスキーを設定
        - NEW_RELIC_LICENSE_KEY